name: Publish to crates.io

on:
  push:
    tags:
      - "v*"
      - "backon-macros-v*"

jobs:
  publish:
    name: Publish crate
    runs-on: ubuntu-latest
    environment: release
    permissions:
      id-token: write
    strategy:
      matrix:
        include:
          - crate: backon
            tag_prefix: v
          - crate: backon-macros
            tag_prefix: backon-macros-v
    steps:
      - uses: actions/checkout@v6
        if: ${{ startsWith(github.ref_name, matrix.tag_prefix) }}
      - name: Authenticate with crates.io
        if: ${{ startsWith(github.ref_name, matrix.tag_prefix) }}
        uses: rust-lang/crates-io-auth-action@v1
        id: auth
      - name: Publish to crates.io
        if: ${{ startsWith(github.ref_name, matrix.tag_prefix) }}
        run: cargo publish -p ${{ matrix.crate }}
        env:
          CARGO_REGISTRY_TOKEN: ${{ steps.auth.outputs.token }}
